### ISSUE TITLE
BUG — contaminated code-review benchmark path crashes aggregate validation on main

### ISSUE THREAD

**Issue by Blummer92** [Blummer92/agent-os#2232]
## Summary

Current canonical `main` at `fa90c85d370f969a1525cbf72985199c23aa1891` contains a deterministic constructor-arity defect in `scripts/agent_os_pr_remediation/code_review_benchmark.py`.

`CaseScore` now requires the non-default field `unsupported_claims`, but the contaminated-run early-return path still constructs `CaseScore` with the older positional argument count. When that path executes, aggregate validation raises `TypeError: CaseScore.__init__() missing 1 required positional argument: 'unsupported_claims'`.

This exact failure is already recorded as an unrelated root aggregate failure in PR #2228, so it can turn otherwise unrelated PRs red.

## Proof on current main

`CaseScore` declares required fields through `unsupported_claims`.

The current contaminated-run branch is:

```python
if run.contaminated or run.contamination_reasons:
    return CaseScore(False,0,0,0,0,0,0,0,0,0,0,0,0,0)
```

That constructor omits the required `unsupported_claims` value.

The existing regression `test_contaminated_run_ineligible` exercises this path, so the defect is reproducible in the canonical test suite rather than inferred from PR UI state.

## Objective

Repair the contaminated-run `CaseScore` construction without changing benchmark semantics, authority fields, scorer versions, or public behavior beyond eliminating the crash.

## Bounded scope

- `scripts/agent_os_pr_remediation/code_review_benchmark.py`
- `tests/agent_os_pr_remediation/test_code_review_benchmark.py`
- directly corresponding documentation only if validation proves it necessary

## Required implementation behavior

- Preserve contaminated runs as `eligible=False`.
- Set every score/metric field, including `unsupported_claims`, to the existing zero-value semantics.
- Preserve all authorization booleans at their existing false defaults.
- Prefer explicit keyword construction for this exceptional early-return path so future additive fields do not silently shift positional meaning.
- Strengthen the contaminated-run regression to assert the returned zero-value contract, not merely `eligible=False`.

## Non-goals / excluded surfaces

- No `.github/workflows/**` changes.
- No required-check, ruleset, or branch-protection changes.
- No benchmark scoring-policy redesign.
- No `BENCHMARK_VERSION` / `SCORER_VERSION` change unless existing tests prove one is contractually required.
- No credentials, Cloud, production, external-system writes, merge, or issue closure.

## Validation

Focused:

```bash
python -m pytest tests/agent_os_pr_remediation/test_code_review_benchmark.py
```

Then current repository aggregate / exact-head CI under the existing validation lane.

## Acceptance criteria

- [ ] Current-main contaminated benchmark reproduction no longer raises constructor `TypeError`.
- [ ] Contaminated runs remain ineligible and all score fields remain zero/false as intended.
- [ ] Existing benchmark tests pass.
- [ ] Exact-head aggregate validation no longer fails on the `CaseScore(... unsupported_claims)` defect.
- [ ] No workflow/protected-setting mutation is used to make CI green.

## Definition of done

A single non-protected branch and PR contain the bounded code/test repair, focused regression coverage passes, and authoritative exact-head validation demonstrates that this root `main` failure is removed. Merge and issue closure remain separately unauthorized.

## Required final report

- files changed
- tests run
- docs updated
- unresolved blockers
- handoff recommendations
- remaining risks

### Issue tier

tier:1-standard-implementation

### Primary owner

owner:github-service-agent

### Readiness candidate

status:ready

### Work type

type:bug

### Source of truth

GitHub

### External write boundary

no-external-write

### Scope and non-goals

Scope:
- Repair only the contaminated-run `CaseScore` construction and its directly corresponding regression coverage.
- Preserve current benchmark semantics, versions, authority defaults, and exact-head validation requirements.

Non-goals:
- No workflow, protected-setting, required-check, credential, Cloud, production, merge, or issue-closure changes.

### Allowed files, areas, or governed surfaces

Allowed:
- scripts/agent_os_pr_remediation/code_review_benchmark.py
- tests/agent_os_pr_remediation/test_code_review_benchmark.py

Forbidden or protected:
- .github/workflows
- protected settings, rulesets, required checks, credentials, Cloud, production, external systems

### Prior scope, duplicate, and supersession review

The defect was isolated from PR #2228's unrelated aggregate failure evidence. Search found no existing open issue owning the exact `CaseScore(... unsupported_claims)` contaminated-run constructor failure, so #2232 is the canonical implementation issue rather than a duplicate or retired-scope revival.

### Documentation impact

docs-not-required

### Documentation exemption reason

The repair restores the already-intended contaminated-run zero/ineligible score contract and does not change documented behavior, operator guidance, benchmark/scorer versions, or public scoring semantics.

### Required tests, validation, and documentation

Tests:
- python -m pytest tests/agent_os_pr_remediation/test_code_review_benchmark.py
- ./scripts/validate-all.sh through the existing exact-head Agent OS Validation Gate final-candidate route

Docs:
- not applicable; behavior contract is unchanged

### Dependencies and blockers

Dependencies: none beyond the existing Agent OS Validation Gate and current exact-head validation policy.
Blockers: authoritative final-candidate aggregate validation must pass before Ready-for-Review.

### Acceptance criteria and definition of done

Acceptance criteria:
- [ ] Current-main contaminated benchmark reproduction no longer raises constructor `TypeError`.
- [ ] Contaminated runs remain ineligible and all score fields remain zero/false as intended.
- [ ] Existing benchmark tests pass.
- [ ] Exact-head aggregate validation no longer fails on the `CaseScore(... unsupported_claims)` defect.
- [ ] No workflow/protected-setting mutation is used to make CI green.

Definition of done:
- [ ] One non-protected branch and PR contain the bounded repair.
- [ ] Required exact-head validation passes.
- [ ] Ready-for-Review is reached only after current-head evidence is clean.
- [ ] Merge and issue closure remain separate governed decisions.

### Safety confirmation

- [x] No direct push to main, automatic merge, or autonomous issue closure is authorized.
- [x] No production, governed-field, source-of-truth, sharing, or external-system write is authorized without explicit approval.
- [x] Final implementation reporting will include files changed, tests run, docs updated, blockers, handoffs, and remaining risks.

**Comment by Blummer92** [comment]
Implementation continuation checkpoint for #2232:

- Existing lineage retained: PR #2233 / `agent/2232-fix-contaminated-benchmark-score`.
- Current exact PR head: `49e1e003ac792e6b8d4a255f4b5c9c9e8f516390`.
- Repair remains bounded to `code_review_benchmark.py` plus its direct regression test.
- Current validation-plan check succeeded and selected aggregate validation.
- Issue Acceptance exposed legacy metadata/reporting gaps rather than a new code failure. Relevant CKR6 Lessons Learned were re-consulted before this correction; no new implementation hypothesis was introduced.
- Canonical tiered issue metadata has now been appended using explicit current evidence; the PR report was also corrected to include every required final-report heading and the exact validation command.
- Authoritative exact-head aggregate validation is still required before Ready-for-Review. No workflow/protected-setting bypass, merge, or closure is authorized.
